// GENERATED by scripts/gen_ui_sources.py — do not edit. Source: backend/studio/constants.py


export type ActionStatus = "Draft" | "Queued" | "Delivering" | "Delivered" | "Processing" | "StateChanged" | "ResolvedNoTransition" | "NotDelivered" | "DeliveryUncertain" | "ReconciliationRequired" | "Failed" | "Cancelled"
export const ACTION_STATUSES: readonly ActionStatus[] = ["Draft", "Queued", "Delivering", "Delivered", "Processing", "StateChanged", "ResolvedNoTransition", "NotDelivered", "DeliveryUncertain", "ReconciliationRequired", "Failed", "Cancelled"]

export type IntentState = "Idle" | "Queued" | "Running" | "WaitingForYou" | "Paused" | "Parked" | "Interrupted" | "ReconciliationRequired" | "RetryEligible" | "CircuitOpen" | "Failed" | "Completed" | "Archived"
export const INTENT_STATES: readonly IntentState[] = ["Idle", "Queued", "Running", "WaitingForYou", "Paused", "Parked", "Interrupted", "ReconciliationRequired", "RetryEligible", "CircuitOpen", "Failed", "Completed", "Archived"]

export type ActionType = "gate" | "revision" | "question" | "missing_input" | "recovery" | "delivery_uncertain" | "failure" | "circuit_breaker" | "install_conflict" | "budget_stop" | "run" | "resume" | "force_stop" | "prepare_commit"
export const ACTION_TYPES: readonly ActionType[] = ["gate", "revision", "question", "missing_input", "recovery", "delivery_uncertain", "failure", "circuit_breaker", "install_conflict", "budget_stop", "run", "resume", "force_stop", "prepare_commit"]

export type Severity = "critical" | "blocking" | "attention" | "info"
export const SEVERITIES: readonly Severity[] = ["critical", "blocking", "attention", "info"]

export type FindingSeverity = "blocking" | "warn" | "info"
export const FINDING_SEVERITIES: readonly FindingSeverity[] = ["blocking", "warn", "info"]

export type Source = "studio" | "aidlc" | "kirocrew" | "git" | "slack"
export const SOURCES: readonly Source[] = ["studio", "aidlc", "kirocrew", "git", "slack"]

export type RiskClass = "read" | "studio_only" | "human_lane" | "admin" | "host_control"
export const RISK_CLASSES: readonly RiskClass[] = ["read", "studio_only", "human_lane", "admin", "host_control"]

export type LeaseKind = "execution" | "admin"
export const LEASE_KINDS: readonly LeaseKind[] = ["execution", "admin"]

export type InstallStatus = "not_installed" | "installed" | "drift" | "recovery_required"
export const INSTALL_STATUSES: readonly InstallStatus[] = ["not_installed", "installed", "drift", "recovery_required"]

export type Availability = "available" | "moved" | "permission_denied" | "unavailable" | "identity_unprovable"
export const AVAILABILITIES: readonly Availability[] = ["available", "moved", "permission_denied", "unavailable", "identity_unprovable"]

export type Ownership = "framework" | "framework-mutable" | "merge" | "shell"
export const OWNERSHIP_KINDS: readonly Ownership[] = ["framework", "framework-mutable", "merge", "shell"]

export type StageState = "not_started" | "in_progress" | "awaiting_approval" | "revising" | "completed" | "skipped" | "unknown"
export const STAGE_STATES: readonly StageState[] = ["not_started", "in_progress", "awaiting_approval", "revising", "completed", "skipped", "unknown"]

export type Decision = "approve" | "request_changes" | "accept_as_is" | "approve_plan" | "request_plan_changes" | "confirm_summary" | "answers" | "provide_input" | "run" | "resume" | "prepare_commit" | "force_stop" | "rebind_session" | "mark_not_delivered" | "acknowledge" | "reconcile" | "resubmit" | "retry_now" | "keep_paused" | "run_now" | "pick_intent"
export const DECISIONS: readonly Decision[] = ["approve", "request_changes", "accept_as_is", "approve_plan", "request_plan_changes", "confirm_summary", "answers", "provide_input", "run", "resume", "prepare_commit", "force_stop", "rebind_session", "mark_not_delivered", "acknowledge", "reconcile", "resubmit", "retry_now", "keep_paused", "run_now", "pick_intent"]

export type Phase = "initialization" | "ideation" | "inception" | "construction" | "operation"
export const PHASES: readonly Phase[] = ["initialization", "ideation", "inception", "construction", "operation"]

export type AdvisorKind = "gate_analysis" | "question_draft" | "question_explain" | "request_changes_draft" | "diagnose" | "plan_draft"
export const ADVISOR_KINDS: readonly AdvisorKind[] = ["gate_analysis", "question_draft", "question_explain", "request_changes_draft", "diagnose", "plan_draft"]

export type AdvisorCardlessKind = "plan_draft"
export const ADVISOR_CARDLESS_KINDS: readonly AdvisorCardlessKind[] = ["plan_draft"]

/** Statuses that keep a card in the queue, and the terminal ones. */
export const LIVE_ACTION_STATUS: readonly ActionStatus[] = ["Queued", "Delivering", "Delivered", "Processing", "DeliveryUncertain", "ReconciliationRequired", "NotDelivered", "Failed"]
export const TERMINAL_ACTION_STATUS: readonly ActionStatus[] = ["StateChanged", "ResolvedNoTransition", "Cancelled"]

/** Machine-lane features are unavailable in v1; the UI shows this reason code. */
export const MACHINE_LANE_REASON = "s12_unproven"
export const ACCEPT_AS_IS_MIN_ATTEMPT = 4
export const DEEP_LINK_BASE = "/apps/aidlc-studio"
