// GENERATED by scripts/gen_ui_sources.py — do not edit. Source: docs/design/wire-text.json


export const WIRE = {
  APPROVE: "Approve",
  REQUEST_CHANGES_PREFIX: "Request Changes: ",
  ACCEPT_AS_IS: "Accept as-is",
  APPROVE_PLAN: "Approve Plan",
  LOOKS_CORRECT: "Looks correct",
  SUMMARY_REQUEST_CHANGES_PREFIX: "Request changes: ",
  ANSWER_LINE: "Q{index}: {answer}",
  ANSWER_JOINER: "\n",
  MULTI_SELECT_JOINER: ", ",
  RUN: "/aidlc",
  RESUME: "/aidlc --resume",
  SCOPE_PREFIX: "/aidlc --scope ",
  PREPARE_COMMIT: "Please prepare a commit for the current AI-DLC changes. Do not push.",
  GROUPED_ANSWER_SUFFIX: "\n\nStudio grouped-answer delivery: this is one human reply. Apply each Q<n> answer to its matching [Answer] tag. Record all Q<n> answers together in ONE aidlc-log.ts answer --details call, preserving their text; do not record separate answer receipts for each question. Then present the next human checkpoint and wait.",
} as const

export type WireKey = keyof typeof WIRE

/** Every protocol string, for the parity test that compares this file with the backend. */
export const WIRE_TEXT_SOURCE = 'docs/design/wire-text.json'
