#!/usr/bin/env python3
"""Generate the UI source files that must never drift from the backend.

Three things exist in two languages and must be byte-identical in both: the protocol wire text, the
error-code table, and the canonical enums. Hand-maintaining a TypeScript copy of each guarantees they
diverge, and a divergence in the wire text means Studio sends a string the AI-DLC conductor does not
recognise — a silent wrong decision. So they are generated here from the single sources:

  docs/design/wire-text.json   -> ui/src/lib/wire.generated.ts
  backend/studio/errors.py     -> ui/src/lib/errorCodes.generated.ts
  backend/studio/constants.py  -> ui/src/lib/enums.generated.ts

Run it after changing any of those, and in CI (`scripts/check.sh` re-runs it and fails if the working
tree changed). Generated files carry a header saying so and are never edited by hand.
"""
from __future__ import annotations

import importlib.machinery
import importlib.util
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "ui" / "src" / "lib"
HEADER = "// GENERATED by scripts/gen_ui_sources.py — do not edit. Source: {source}\n"


def load_backend_module(name: str):
    """Import one backend/studio module through the app's own private namespace."""
    ns = "_aidlc_studio_backend"
    if ns not in sys.modules:
        spec = importlib.machinery.ModuleSpec(ns, None, is_package=True)
        module = importlib.util.module_from_spec(spec)
        module.__path__ = [str(ROOT / "backend")]  # type: ignore[attr-defined]
        sys.modules[ns] = module
    return importlib.import_module(f"{ns}.studio.{name}")


def ts_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def gen_wire() -> str:
    data = json.loads((ROOT / "docs" / "design" / "wire-text.json").read_text("utf-8"))
    constants = data["constants"]
    # WIRE_APPROVE -> APPROVE, so the UI reads WIRE.APPROVE while the backend reads WIRE_APPROVE.
    entries = {k.removeprefix("WIRE_"): v for k, v in constants.items()}
    lines = [HEADER.format(source="docs/design/wire-text.json"), "", "export const WIRE = {"]
    for key, value in entries.items():
        lines.append(f"  {key}: {ts_string(value)},")
    lines += [
        "} as const",
        "",
        "export type WireKey = keyof typeof WIRE",
        "",
        "/** Every protocol string, for the parity test that compares this file with the backend. */",
        "export const WIRE_TEXT_SOURCE = 'docs/design/wire-text.json'",
        "",
    ]
    return "\n".join(lines)


def gen_error_codes() -> str:
    errors = load_backend_module("errors")
    codes = dict(sorted(errors.ERROR_CODES.items()))
    lines = [
        HEADER.format(source="backend/studio/errors.py"),
        "",
        "/** code -> HTTP status. The UI renders `errors.<code>` from its catalog and never parses prose. */",
        "export const ERROR_CODES = {",
    ]
    for code, status in codes.items():
        lines.append(f"  {code}: {status},")
    lines += [
        "} as const",
        "",
        "export type ErrorCode = keyof typeof ERROR_CODES",
        "",
        "export interface StudioApiError { error: string; code: ErrorCode | string; details: Record<string, unknown> }",
        "",
    ]
    return "\n".join(lines)


def gen_enums() -> str:
    C = load_backend_module("constants")
    # (TypeScript type name, exported array name, values) — the array name is explicit rather than
    # derived, because pluralising "ActionStatus" mechanically produced "ACTION_STATUSS".
    named = {
        "ActionStatus": C.ACTION_STATUS,
        "IntentState": C.INTENT_STATE,
        "ActionType": C.ACTION_TYPE,
        "Severity": C.SEVERITY,
        "FindingSeverity": C.FINDING_SEVERITY,
        "Source": C.SOURCE,
        "RiskClass": C.RISK_CLASS,
        "LeaseKind": C.LEASE_KIND,
        "InstallStatus": C.INSTALL_STATUS,
        "Availability": C.AVAILABILITY,
        "Ownership": C.OWNERSHIP,
        "StageState": C.STAGE_STATE,
        "Decision": C.DECISION_KIND,
        "Phase": C.PHASES,
        # Advisor kinds are generated so the i18n parity test can demand a label per kind and the UI
        # can never hand-write a union that lags the backend by the one kind a draft is stuck in.
        "AdvisorKind": C.ADVISOR_KINDS,
        "AdvisorCardlessKind": C.ADVISOR_CARDLESS_KINDS,
    }
    lines = [HEADER.format(source="backend/studio/constants.py"), ""]
    array_names = {
        "ActionStatus": "ACTION_STATUSES",
        "IntentState": "INTENT_STATES",
        "ActionType": "ACTION_TYPES",
        "Severity": "SEVERITIES",
        "FindingSeverity": "FINDING_SEVERITIES",
        "Source": "SOURCES",
        "RiskClass": "RISK_CLASSES",
        "LeaseKind": "LEASE_KINDS",
        "InstallStatus": "INSTALL_STATUSES",
        "Availability": "AVAILABILITIES",
        "Ownership": "OWNERSHIP_KINDS",
        "StageState": "STAGE_STATES",
        "Decision": "DECISIONS",
        "Phase": "PHASES",
        "AdvisorKind": "ADVISOR_KINDS",
        "AdvisorCardlessKind": "ADVISOR_CARDLESS_KINDS",
    }
    for name, values in named.items():
        union = " | ".join(ts_string(v) for v in values)
        lines.append(f"export type {name} = {union}")
        lines.append(
            f"export const {array_names[name]}: readonly {name}[] = "
            f"[{', '.join(ts_string(v) for v in values)}]"
        )
        lines.append("")
    lines += [
        "/** Statuses that keep a card in the queue, and the terminal ones. */",
        "export const LIVE_ACTION_STATUS: readonly ActionStatus[] = ["
        + ", ".join(ts_string(v) for v in C.LIVE_ACTION_STATUS)
        + "]",
        "export const TERMINAL_ACTION_STATUS: readonly ActionStatus[] = ["
        + ", ".join(ts_string(v) for v in C.TERMINAL_ACTION_STATUS)
        + "]",
        "",
        "/** Machine-lane features are unavailable in v1; the UI shows this reason code. */",
        f"export const MACHINE_LANE_REASON = {ts_string(C.MACHINE_LANE_REASON)}",
        f"export const ACCEPT_AS_IS_MIN_ATTEMPT = {C.ACCEPT_AS_IS_MIN_ATTEMPT}",
        f"export const DEEP_LINK_BASE = {ts_string(C.DEEP_LINK_BASE)}",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    written = []
    for name, text in (
        ("wire.generated.ts", gen_wire()),
        ("errorCodes.generated.ts", gen_error_codes()),
        ("enums.generated.ts", gen_enums()),
    ):
        path = OUT / name
        before = path.read_text("utf-8") if path.is_file() else ""
        if before != text:
            path.write_text(text, encoding="utf-8")
            written.append(name)
    print("generated:", ", ".join(written) if written else "no changes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
